In [1]:
import pandas as pd

- Series → One-dimensional (like a single column in Excel)
- DataFrame → Two-dimensional (like a full spreadsheet or SQL table)

In [2]:
s = pd.Series([1,4,56,23,56,98,56])

In [3]:
s

0     1
1     4
2    56
3    23
4    56
5    98
6    56
dtype: int64

In [4]:
type(s)

pandas.core.series.Series

In [5]:
print(s)

0     1
1     4
2    56
3    23
4    56
5    98
6    56
dtype: int64

In [6]:
# custom index
s1 = pd.Series([1,4,56,23,56,98,56], index=["A","B","C","D","E","F","G"])

In [7]:
print(s1)

A     1
B     4
C    56
D    23
E    56
F    98
G    56
dtype: int64

In [8]:
s1["A"]

np.int64(1)

- A pandas.Series may look similar to a Python dictionary because both store data
with labels, but a Series offers much more. Unlike a dictionary, a Series supports
fast vectorized operations.
- It also allows both label-based and position
based access, and integrates seamlessly with the pandas ecosystem, especially
DataFrames. 
- While a dictionary is great for simple key–value storage, a Series is
better suited for data analysis and manipulation tasks where performance,
flexibility, and built-in functionality matter.

### Dataframe

- A 
DataFrame is like a dictionary of Series — multiple columns with labels.

In [9]:
data = {
    "name": ["Alice", "Bob", "Charlie"],
    "age": [25, 30, 35],
    "city": ["Delhi", "Mumbai", "Bangalore"]
}

In [10]:
data

{'name': ['Alice', 'Bob', 'Charlie'],
 'age': [25, 30, 35],
 'city': ['Delhi', 'Mumbai', 'Bangalore']}

In [12]:
# tabular data ko python me store kara efficiently
df = pd.DataFrame(data)
print(df)

      name  age       city
0    Alice   25      Delhi
1      Bob   30     Mumbai
2  Charlie   35  Bangalore

In [16]:
# Each column in a DataFrame is a Series .
df

      name  age       city
0    Alice   25      Delhi
1      Bob   30     Mumbai
2  Charlie   35  Bangalore

In [19]:
df.index # row labels

RangeIndex(start=0, stop=3, step=1)

In [20]:
df.columns # column labels

Index(['name', 'age', 'city'], dtype='object')

In [21]:
df.index = ["a", "b", "c"]
df.columns = ["Name", "Age", "City"]

In [22]:
df

      Name  Age       City
a    Alice   25      Delhi
b      Bob   30     Mumbai
c  Charlie   35  Bangalore