## Creating DataFrames
- Let’s look at different ways to create a Pandas 
DataFrame — the core data
structure you’ll be using 90% of the time in data science.

In [1]:
import pandas as pd

- From Python Lists

In [2]:
data = [['harry',34], ['jack',67], ['gill',23], ['ajay',56]]

In [3]:
data

[['harry', 34], ['jack', 67], ['gill', 23], ['ajay', 56]]

In [4]:
df = pd.DataFrame(data, columns=['Name', 'Marks'])

In [5]:
df

    Name  Marks
0  harry     34
1   jack     67
2   gill     23
3   ajay     56

- From Dictionary of Lists

In [6]:
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35]
}
df = pd.DataFrame(data)
df

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [7]:
df.index = ['1','2','3']

In [8]:
df

      Name  Age
1    Alice   25
2      Bob   30
3  Charlie   35

In [9]:
# Each key becomes a column, and each list is the column data.

- From NumPy Arrays

In [10]:
import numpy as np

In [11]:
arr = np.array([[1,2], [5,6]])

In [12]:
df = pd.DataFrame(arr, columns=['A','B'])

In [13]:
df

   A  B
0  1  2
1  5  6

- From CSV Files

In [14]:
df = pd.read_excel("data.xlsx")
df

     Name School   Marks
0      Om     SHS     87
1    Ajay    BNSD     45
2  Sachin    VSPS     87
3   Rahul     MHS     36
4   Sagar     UPS     46

In [15]:
df = pd.read_csv("data.csv")
df

     Name School   Marks
0      Om     SHS     87
1    Ajay    BNSD     45
2  Sachin    VSPS     87
3   Rahul     MHS     36
4   Sagar     UPS     46

- JSON file

In [16]:
df = pd.read_json("data.json")

In [17]:
df

    Name  Age
0     Om   21
1  Harry   40

- From URL

In [18]:
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"
df = pd.read_csv(url)

In [19]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

## EDA - Exploratory Data Analysis

- Exploratory Data Analysis (EDA) is an essential first step in any data science project.
- It involves taking a deep look at the dataset to understand its structure, spot
patterns, identify anomalies, and uncover relationships between variables. 
- This process includes generating summary statistics, checking for missing or duplicate
data, and creating visualizations like histograms, box plots, and scatter plots. The
goal of EDA is to get a clear picture of what the data is telling you before applying
any analysis or machine learning models.

In [20]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [21]:
df.tail()

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [23]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [24]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [25]:
df.shape

(244, 7)

In [26]:
df.index

RangeIndex(start=0, stop=244, step=1)