## Data Selection & Filtering

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data2.csv")

In [3]:
df

      Actor       Film   Year      Genre  Box Office  IMDB
0       SRK      Pathan  2001     Action        1050   7.2
1    Salman       Tiger  2002     Action         456   9.8
2     Aamir      Dangal  2003  Biography         120   5.6
3    Akshay   Good News  2004     Comedy         100   5.6
4      Ajay     Singham  2005     Action         480   4.6
5     Varun        HSKD  2006     Action         456   7.8
6  Siddhant  Gehraiyaan  2007   Thriller         145   8.6
7     Vicky    Shiva Ji  2008     Action         254   3.2
8    Ranbir        YJHD  2009    Rom-Com         154   5.6
9   Ranveer   Dhurandar  2010     Action        1700  10.0

In [4]:
# selecting colmn
df['Actor']

0         SRK
1      Salman
2       Aamir
3      Akshay
4        Ajay
5       Varun
6    Siddhant
7       Vicky
8      Ranbir
9     Ranveer
Name: Actor, dtype: object

In [5]:
df['Actor'][3]

'Akshay'

In [6]:
type(df['Actor'])

pandas.core.series.Series

In [7]:
type(df)

pandas.core.frame.DataFrame

In [8]:
df[['Actor','IMDB']]

      Actor  IMDB
0       SRK   7.2
1    Salman   9.8
2     Aamir   5.6
3    Akshay   5.6
4      Ajay   4.6
5     Varun   7.8
6  Siddhant   8.6
7     Vicky   3.2
8    Ranbir   5.6
9   Ranveer  10.0

In [9]:
df

      Actor       Film   Year      Genre  Box Office  IMDB
0       SRK      Pathan  2001     Action        1050   7.2
1    Salman       Tiger  2002     Action         456   9.8
2     Aamir      Dangal  2003  Biography         120   5.6
3    Akshay   Good News  2004     Comedy         100   5.6
4      Ajay     Singham  2005     Action         480   4.6
5     Varun        HSKD  2006     Action         456   7.8
6  Siddhant  Gehraiyaan  2007   Thriller         145   8.6
7     Vicky    Shiva Ji  2008     Action         254   3.2
8    Ranbir        YJHD  2009    Rom-Com         154   5.6
9   Ranveer   Dhurandar  2010     Action        1700  10.0

In [10]:
# selecting rows
df.loc[1] # by label if changed to 'A'

Actor         Salman
Film           Tiger
Year            2002
Genre         Action
Box Office       456
IMDB             9.8
Name: 1, dtype: object

In [11]:
df.iloc[1] # by position (index)

Actor         Salman
Film           Tiger
Year            2002
Genre         Action
Box Office       456
IMDB             9.8
Name: 1, dtype: object

In [12]:
# select specific rows and columns
df.loc[8, 'IMDB']

np.float64(5.6)

In [13]:
df.iloc[8, 5]

np.float64(5.6)

In [14]:
df.loc[0:2, ['Actor', 'IMDB']] # inclusive

    Actor  IMDB
0     SRK   7.2
1  Salman   9.8
2   Aamir   5.6

In [15]:
df.iloc[0:2, 0:2] # exclusive

    Actor   Film
0     SRK  Pathan
1  Salman   Tiger

In [16]:
df.at[0, 'Actor'] # for single element

'SRK'

In [17]:
df.iat[0, 0]

'SRK'

- filtering

In [18]:
df[df['IMDB'] > 6]

      Actor       Film   Year     Genre  Box Office  IMDB
0       SRK      Pathan  2001    Action        1050   7.2
1    Salman       Tiger  2002    Action         456   9.8
5     Varun        HSKD  2006    Action         456   7.8
6  Siddhant  Gehraiyaan  2007  Thriller         145   8.6
9   Ranveer   Dhurandar  2010    Action        1700  10.0

In [19]:
df[df['IMDB'] > 6]['Actor']

0         SRK
1      Salman
5       Varun
6    Siddhant
9     Ranveer
Name: Actor, dtype: object

In [20]:
df.columns
df.columns = df.columns.str.strip()  # remove spaces

In [21]:
df[(df['IMDB'] > 5) & (df['Year'] > 2003)]

      Actor        Film  Year     Genre  Box Office  IMDB
3    Akshay   Good News  2004    Comedy         100   5.6
5     Varun        HSKD  2006    Action         456   7.8
6  Siddhant  Gehraiyaan  2007  Thriller         145   8.6
8    Ranbir        YJHD  2009   Rom-Com         154   5.6
9   Ranveer   Dhurandar  2010    Action        1700  10.0

In [22]:
df.query("Year > 2001 and IMDB > 6")

      Actor        Film  Year     Genre  Box Office  IMDB
1    Salman       Tiger  2002    Action         456   9.8
5     Varun        HSKD  2006    Action         456   7.8
6  Siddhant  Gehraiyaan  2007  Thriller         145   8.6
9   Ranveer   Dhurandar  2010    Action        1700  10.0

In [23]:
df.query("Actor == 'Akshay' and Genre == 'Comedy'")

    Actor       Film  Year   Genre  Box Office  IMDB
3  Akshay  Good News  2004  Comedy         100   5.6

In [24]:
# If a column name has spaces, use backticks (`)
# df.query("`first name` == 'Alice'")

In [25]:
# You can use @ to reference Python variables
rating = 5
df.query("IMDB > @rating")

      Actor        Film  Year      Genre  Box Office  IMDB
0       SRK      Pathan  2001     Action        1050   7.2
1    Salman       Tiger  2002     Action         456   9.8
2     Aamir      Dangal  2003  Biography         120   5.6
3    Akshay   Good News  2004     Comedy         100   5.6
5     Varun        HSKD  2006     Action         456   7.8
6  Siddhant  Gehraiyaan  2007   Thriller         145   8.6
8    Ranbir        YJHD  2009    Rom-Com         154   5.6
9   Ranveer   Dhurandar  2010     Action        1700  10.0

In [26]:

df2 = df[['Actor', 'IMDB']].copy()

In [27]:
df2

      Actor  IMDB
0       SRK   7.2
1    Salman   9.8
2     Aamir   5.6
3    Akshay   5.6
4      Ajay   4.6
5     Varun   7.8
6  Siddhant   8.6
7     Vicky   3.2
8    Ranbir   5.6
9   Ranveer  10.0

In [28]:
df2.loc[0, 'Actor'] = 'Harry' # changes are not made to df

In [29]:
df2

      Actor  IMDB
0     Harry   7.2
1    Salman   9.8
2     Aamir   5.6
3    Akshay   5.6
4      Ajay   4.6
5     Varun   7.8
6  Siddhant   8.6
7     Vicky   3.2
8    Ranbir   5.6
9   Ranveer  10.0

In [30]:
df

      Actor        Film  Year      Genre  Box Office  IMDB
0       SRK      Pathan  2001     Action        1050   7.2
1    Salman       Tiger  2002     Action         456   9.8
2     Aamir      Dangal  2003  Biography         120   5.6
3    Akshay   Good News  2004     Comedy         100   5.6
4      Ajay     Singham  2005     Action         480   4.6
5     Varun        HSKD  2006     Action         456   7.8
6  Siddhant  Gehraiyaan  2007   Thriller         145   8.6
7     Vicky    Shiva Ji  2008     Action         254   3.2
8    Ranbir        YJHD  2009    Rom-Com         154   5.6
9   Ranveer   Dhurandar  2010     Action        1700  10.0

In [31]:
# .query() returns a copy, not a view