## Data Cleaning and Pre-Processing

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data_cleaning_sample.csv")

In [3]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [4]:
df.isnull()

    Name    Age   City  Gender  Email  Join Date
0  False  False  False   False  False      False
1  False   True  False   False  False      False
2  False  False  False   False  False      False
3  False   True  False   False  False      False
4  False  False  False   False  False      False
5   True  False  False   False  False       True
6  False  False  False   False  False      False
7  False  False  False   False  False      False
8  False   True  False   False  False      False

In [5]:
df.isnull().sum()

Name         1
Age          3
City         0
Gender       0
Email        0
Join Date    1
dtype: int64

In [6]:
df.dropna() # drops all rows with NULL values

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [7]:
df.dropna(axis=1) # drops all columns with NULL values

          City Gender              Email
0     New York      F  alice@example.com
1        Delhi      M    charlie@example
2  Los Angeles      M    bob@example.com
3        Delhi      M    charlie@example
4       Mumbai      M  david@example.com
5        Delhi      F     eve@domain.com
6     New York      F  alice@example.com
7     New York      F  alice@example.com
8        Delhi      M    charlie@example

In [8]:
df.fillna(0) # filling missing values and Replace NaN with 0

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5        0  28.0        Delhi      F     eve@domain.com           0
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   0.0        Delhi      M    charlie@example  20-07-2021

In [9]:
df["Age"].fillna(df["Age"].mean()) # Replace with mean

0    25.000000
1    25.833333
2    30.000000
3    25.833333
4    22.000000
5    28.000000
6    25.000000
7    25.000000
8    25.833333
Name: Age, dtype: float64

In [10]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [11]:
df.ffill() # Forward fill

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    David  28.0        Delhi      F     eve@domain.com  12-11-2019
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie  25.0        Delhi      M    charlie@example  20-07-2021

In [12]:
df.bfill() # Backward fill

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  22.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    Alice  28.0        Delhi      F     eve@domain.com  01-05-2021
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

### Detecting & Removing Duplicates

In [13]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [14]:
df.duplicated() # reads from top to bottom

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [15]:
df.drop_duplicates()  # Remove duplicate rows

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN

In [16]:
df.duplicated(subset=["Name", "Age"])

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [17]:
# All string methods are not supported here

### String Operations with .str

In [18]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [19]:
df["Name"].str.lower()  # Converts all names to lowercase.

0      alice
1    charlie
2        bob
3    charlie
4      david
5        NaN
6      alice
7      alice
8    charlie
Name: Name, dtype: object

In [20]:
df["City"].str.contains("delhi", case=False) # Checks if 'delhi' is in the city name, case-insensitive.

0    False
1     True
2    False
3     True
4    False
5     True
6    False
7    False
8     True
Name: City, dtype: bool

In [21]:
df["Email"].str.split("@") # Outputs a pandas Series where each element is a list

0    [alice, example.com]
1      [charlie, example]
2      [bob, example.com]
3      [charlie, example]
4    [david, example.com]
5       [eve, domain.com]
6    [alice, example.com]
7    [alice, example.com]
8      [charlie, example]
Name: Email, dtype: object

In [22]:
type(df["Email"].str.split("@")[0])

list

### Type Conversions with .astype()

In [23]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [24]:
df2 = df.dropna().copy()
df2

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [25]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 0 to 7
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       5 non-null      object
 1   Age        5 non-null      float64
 2   City       5 non-null      object
 3   Gender     5 non-null      object
 4   Email      5 non-null      object
 5   Join Date  5 non-null      object
dtypes: float64(1), object(5)
memory usage: 280.0+ bytes

In [26]:
df2["Age"] = df2["Age"].astype('int32')

In [27]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 0 to 7
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       5 non-null      object
 1   Age        5 non-null      int32
 2   City       5 non-null      object
 3   Gender     5 non-null      object
 4   Email      5 non-null      object
 5   Join Date  5 non-null      object
dtypes: int32(1), object(5)
memory usage: 260.0+ bytes

In [28]:
df2

    Name  Age         City Gender              Email   Join Date
0  Alice   25     New York      F  alice@example.com  01-05-2021
2    Bob   30  Los Angeles      M    bob@example.com  15-06-2020
4  David   22       Mumbai      M  david@example.com  12-11-2019
6  Alice   25     New York      F  alice@example.com  01-05-2021
7  Alice   25     New York      F  alice@example.com  01-05-2021

In [29]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [30]:
df.dtypes

Name          object
Age          float64
City          object
Gender        object
Email         object
Join Date     object
dtype: object

### Applying Functions

In [31]:
# .apply() → Apply any function to rows or columns

In [32]:
df2

    Name  Age         City Gender              Email   Join Date
0  Alice   25     New York      F  alice@example.com  01-05-2021
2    Bob   30  Los Angeles      M    bob@example.com  15-06-2020
4  David   22       Mumbai      M  david@example.com  12-11-2019
6  Alice   25     New York      F  alice@example.com  01-05-2021
7  Alice   25     New York      F  alice@example.com  01-05-2021

In [33]:
# we could build a function also
def isMinor(x):
    return "Adult" if x >= 25 else "Minor"
df2["Age Group"] = df2["Age"].apply(lambda x: "Adult" if x >= 25 else "Minor")

In [34]:
df2

    Name  Age         City Gender              Email   Join Date Age Group
0  Alice   25     New York      F  alice@example.com  01-05-2021     Adult
2    Bob   30  Los Angeles      M    bob@example.com  15-06-2020     Adult
4  David   22       Mumbai      M  david@example.com  12-11-2019     Minor
6  Alice   25     New York      F  alice@example.com  01-05-2021     Adult
7  Alice   25     New York      F  alice@example.com  01-05-2021     Adult

In [35]:
# .map() → Element-wise mapping for Series

In [36]:
gender_map = {"M": "Male", "F": "Female"}
df2["Gender"] = df2["Gender"].map(gender_map)

In [37]:
df2

    Name  Age         City  Gender              Email   Join Date Age Group
0  Alice   25     New York  Female  alice@example.com  01-05-2021     Adult
2    Bob   30  Los Angeles    Male    bob@example.com  15-06-2020     Adult
4  David   22       Mumbai    Male  david@example.com  12-11-2019     Minor
6  Alice   25     New York  Female  alice@example.com  01-05-2021     Adult
7  Alice   25     New York  Female  alice@example.com  01-05-2021     Adult

In [38]:
# .replace() → Replace specific values

In [39]:
city_map = {"New York": "New Delhi", "Mumbai": "Navi Mumbai"}
df2["City"] = df2["City"].replace(city_map)

In [40]:
df2

    Name  Age         City  Gender              Email   Join Date Age Group
0  Alice   25    New Delhi  Female  alice@example.com  01-05-2021     Adult
2    Bob   30  Los Angeles    Male    bob@example.com  15-06-2020     Adult
4  David   22  Navi Mumbai    Male  david@example.com  12-11-2019     Minor
6  Alice   25    New Delhi  Female  alice@example.com  01-05-2021     Adult
7  Alice   25    New Delhi  Female  alice@example.com  01-05-2021     Adult

In [41]:
# Data cleaning is where 80% of your time goes in real projects