## Data Transformation
- Once your data is clean, the next step is to reshape, reformat, and reorder it as needed for analysis. 
- Pandas gives you plenty of flexible tools to do this.

In [1]:
import pandas as pd

In [2]:
# Sorting & Ranking

In [3]:
df = pd.read_csv("data2.csv")

In [4]:
df

      Actor       Film   Year      Genre  Box Office  IMDB
0       SRK      Pathan  2001     Action        1050   7.2
1    Salman       Tiger  2002     Action         456   9.8
2     Aamir      Dangal  2003  Biography         120   5.6
3    Akshay   Good News  2004     Comedy         100   5.6
4      Ajay     Singham  2005     Action         480   4.6
5     Varun        HSKD  2006     Action         456   7.8
6  Siddhant  Gehraiyaan  2007   Thriller         145   8.6
7     Vicky    Shiva Ji  2008     Action         254   3.2
8    Ranbir        YJHD  2009    Rom-Com         154   5.6
9   Ranveer   Dhurandar  2010     Action        1700  10.0

In [5]:
df.sort_values("Year")

      Actor       Film   Year      Genre  Box Office  IMDB
0       SRK      Pathan  2001     Action        1050   7.2
1    Salman       Tiger  2002     Action         456   9.8
2     Aamir      Dangal  2003  Biography         120   5.6
3    Akshay   Good News  2004     Comedy         100   5.6
4      Ajay     Singham  2005     Action         480   4.6
5     Varun        HSKD  2006     Action         456   7.8
6  Siddhant  Gehraiyaan  2007   Thriller         145   8.6
7     Vicky    Shiva Ji  2008     Action         254   3.2
8    Ranbir        YJHD  2009    Rom-Com         154   5.6
9   Ranveer   Dhurandar  2010     Action        1700  10.0

In [6]:
df.sort_values("Box Office")

      Actor       Film   Year      Genre  Box Office  IMDB
3    Akshay   Good News  2004     Comedy         100   5.6
2     Aamir      Dangal  2003  Biography         120   5.6
6  Siddhant  Gehraiyaan  2007   Thriller         145   8.6
8    Ranbir        YJHD  2009    Rom-Com         154   5.6
7     Vicky    Shiva Ji  2008     Action         254   3.2
1    Salman       Tiger  2002     Action         456   9.8
5     Varun        HSKD  2006     Action         456   7.8
4      Ajay     Singham  2005     Action         480   4.6
0       SRK      Pathan  2001     Action        1050   7.2
9   Ranveer   Dhurandar  2010     Action        1700  10.0

In [7]:
df.sort_values("Year", ascending=False) # Descending

      Actor       Film   Year      Genre  Box Office  IMDB
9   Ranveer   Dhurandar  2010     Action        1700  10.0
8    Ranbir        YJHD  2009    Rom-Com         154   5.6
7     Vicky    Shiva Ji  2008     Action         254   3.2
6  Siddhant  Gehraiyaan  2007   Thriller         145   8.6
5     Varun        HSKD  2006     Action         456   7.8
4      Ajay     Singham  2005     Action         480   4.6
3    Akshay   Good News  2004     Comedy         100   5.6
2     Aamir      Dangal  2003  Biography         120   5.6
1    Salman       Tiger  2002     Action         456   9.8
0       SRK      Pathan  2001     Action        1050   7.2

In [8]:
df.sort_values(["IMDB", "Year"]) # Sort by multiple columns

      Actor       Film   Year      Genre  Box Office  IMDB
7     Vicky    Shiva Ji  2008     Action         254   3.2
4      Ajay     Singham  2005     Action         480   4.6
2     Aamir      Dangal  2003  Biography         120   5.6
3    Akshay   Good News  2004     Comedy         100   5.6
8    Ranbir        YJHD  2009    Rom-Com         154   5.6
0       SRK      Pathan  2001     Action        1050   7.2
5     Varun        HSKD  2006     Action         456   7.8
6  Siddhant  Gehraiyaan  2007   Thriller         145   8.6
1    Salman       Tiger  2002     Action         456   9.8
9   Ranveer   Dhurandar  2010     Action        1700  10.0

In [9]:
df2 = df.sort_values(["IMDB", "Year"]).copy()
df2

      Actor       Film   Year      Genre  Box Office  IMDB
7     Vicky    Shiva Ji  2008     Action         254   3.2
4      Ajay     Singham  2005     Action         480   4.6
2     Aamir      Dangal  2003  Biography         120   5.6
3    Akshay   Good News  2004     Comedy         100   5.6
8    Ranbir        YJHD  2009    Rom-Com         154   5.6
0       SRK      Pathan  2001     Action        1050   7.2
5     Varun        HSKD  2006     Action         456   7.8
6  Siddhant  Gehraiyaan  2007   Thriller         145   8.6
1    Salman       Tiger  2002     Action         456   9.8
9   Ranveer   Dhurandar  2010     Action        1700  10.0

In [10]:
# Reset the index and drop the old index
df2.reset_index(drop=True, inplace=True)

In [11]:
df2

      Actor       Film   Year      Genre  Box Office  IMDB
0     Vicky    Shiva Ji  2008     Action         254   3.2
1      Ajay     Singham  2005     Action         480   4.6
2     Aamir      Dangal  2003  Biography         120   5.6
3    Akshay   Good News  2004     Comedy         100   5.6
4    Ranbir        YJHD  2009    Rom-Com         154   5.6
5       SRK      Pathan  2001     Action        1050   7.2
6     Varun        HSKD  2006     Action         456   7.8
7  Siddhant  Gehraiyaan  2007   Thriller         145   8.6
8    Salman       Tiger  2002     Action         456   9.8
9   Ranveer   Dhurandar  2010     Action        1700  10.0

In [12]:
df3 = df.sort_values(["IMDB", "Year"]).copy()

In [13]:
df3

      Actor       Film   Year      Genre  Box Office  IMDB
7     Vicky    Shiva Ji  2008     Action         254   3.2
4      Ajay     Singham  2005     Action         480   4.6
2     Aamir      Dangal  2003  Biography         120   5.6
3    Akshay   Good News  2004     Comedy         100   5.6
8    Ranbir        YJHD  2009    Rom-Com         154   5.6
0       SRK      Pathan  2001     Action        1050   7.2
5     Varun        HSKD  2006     Action         456   7.8
6  Siddhant  Gehraiyaan  2007   Thriller         145   8.6
1    Salman       Tiger  2002     Action         456   9.8
9   Ranveer   Dhurandar  2010     Action        1700  10.0

In [14]:
df3.sort_index()

      Actor       Film   Year      Genre  Box Office  IMDB
0       SRK      Pathan  2001     Action        1050   7.2
1    Salman       Tiger  2002     Action         456   9.8
2     Aamir      Dangal  2003  Biography         120   5.6
3    Akshay   Good News  2004     Comedy         100   5.6
4      Ajay     Singham  2005     Action         480   4.6
5     Varun        HSKD  2006     Action         456   7.8
6  Siddhant  Gehraiyaan  2007   Thriller         145   8.6
7     Vicky    Shiva Ji  2008     Action         254   3.2
8    Ranbir        YJHD  2009    Rom-Com         154   5.6
9   Ranveer   Dhurandar  2010     Action        1700  10.0

In [15]:
# RANKING

In [16]:
df2

      Actor       Film   Year      Genre  Box Office  IMDB
0     Vicky    Shiva Ji  2008     Action         254   3.2
1      Ajay     Singham  2005     Action         480   4.6
2     Aamir      Dangal  2003  Biography         120   5.6
3    Akshay   Good News  2004     Comedy         100   5.6
4    Ranbir        YJHD  2009    Rom-Com         154   5.6
5       SRK      Pathan  2001     Action        1050   7.2
6     Varun        HSKD  2006     Action         456   7.8
7  Siddhant  Gehraiyaan  2007   Thriller         145   8.6
8    Salman       Tiger  2002     Action         456   9.8
9   Ranveer   Dhurandar  2010     Action        1700  10.0

In [17]:
df2["Rank"] = df2["IMDB"].rank()

In [18]:
df2

      Actor       Film   Year      Genre  Box Office  IMDB  Rank
0     Vicky    Shiva Ji  2008     Action         254   3.2   1.0
1      Ajay     Singham  2005     Action         480   4.6   2.0
2     Aamir      Dangal  2003  Biography         120   5.6   4.0
3    Akshay   Good News  2004     Comedy         100   5.6   4.0
4    Ranbir        YJHD  2009    Rom-Com         154   5.6   4.0
5       SRK      Pathan  2001     Action        1050   7.2   6.0
6     Varun        HSKD  2006     Action         456   7.8   7.0
7  Siddhant  Gehraiyaan  2007   Thriller         145   8.6   8.0
8    Salman       Tiger  2002     Action         456   9.8   9.0
9   Ranveer   Dhurandar  2010     Action        1700  10.0  10.0

In [19]:
df2["Rank"] = df2["IMDB"].rank(ascending=False, method="dense")

In [20]:
df2

      Actor       Film   Year      Genre  Box Office  IMDB  Rank
0     Vicky    Shiva Ji  2008     Action         254   3.2   8.0
1      Ajay     Singham  2005     Action         480   4.6   7.0
2     Aamir      Dangal  2003  Biography         120   5.6   6.0
3    Akshay   Good News  2004     Comedy         100   5.6   6.0
4    Ranbir        YJHD  2009    Rom-Com         154   5.6   6.0
5       SRK      Pathan  2001     Action        1050   7.2   5.0
6     Varun        HSKD  2006     Action         456   7.8   4.0
7  Siddhant  Gehraiyaan  2007   Thriller         145   8.6   3.0
8    Salman       Tiger  2002     Action         456   9.8   2.0
9   Ranveer   Dhurandar  2010     Action        1700  10.0   1.0

In [21]:
# Renaming Columns

In [22]:
df2.rename(columns={"Rank": "Position"}, inplace=True)

In [23]:
df2

      Actor       Film   Year      Genre  Box Office  IMDB  Position
0     Vicky    Shiva Ji  2008     Action         254   3.2       8.0
1      Ajay     Singham  2005     Action         480   4.6       7.0
2     Aamir      Dangal  2003  Biography         120   5.6       6.0
3    Akshay   Good News  2004     Comedy         100   5.6       6.0
4    Ranbir        YJHD  2009    Rom-Com         154   5.6       6.0
5       SRK      Pathan  2001     Action        1050   7.2       5.0
6     Varun        HSKD  2006     Action         456   7.8       4.0
7  Siddhant  Gehraiyaan  2007   Thriller         145   8.6       3.0
8    Salman       Tiger  2002     Action         456   9.8       2.0
9   Ranveer   Dhurandar  2010     Action        1700  10.0       1.0