## Melt and Pivot

In [1]:
import pandas as pd
 
# Sample DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Math': [85, 78, 92],
    'Science': [90, 82, 89],
    'English': [88, 85, 94]
}
 
df = pd.DataFrame(data)
 
# Display the DataFrame
print(df)

      Name  Math  Science  English
0    Alice    85       90       88
1      Bob    78       82       85
2  Charlie    92       89       94

- melt() — Wide to Long
- id_vars: The columns that you want to keep fixed (these columns will remain as identifiers).
- value_vars: The columns you want to unpivot (the ones you want to "melt" into a single column).    
- var_name: The name to use for the new column that will contain the names of the melted columns (default is 'variable').
- value_name: The name to use for the new column that will contain the values from the melted columns (default is 'value').

In [2]:
df = df.melt(id_vars=["Name"], value_vars=["Math", "Science", "English"], var_name="Subject", value_name="Score")

In [3]:
df

      Name  Subject  Score
0    Alice     Math     85
1      Bob     Math     78
2  Charlie     Math     92
3    Alice  Science     90
4      Bob  Science     82
5  Charlie  Science     89
6    Alice  English     88
7      Bob  English     85
8  Charlie  English     94

Why Use melt() ?
- Data normalization: Helps in transforming data for statistical modeling and data visualization.
- Pivot tables: Many times, plotting functions or statistical models work better with long-format data.

#### pivot

- index="Name": The unique values in the "Name" column will become the rows in the new DataFrame.
- columns="Subject": The unique values in the "Subject" column will become the columns in the new DataFrame.
- values="Score": The values from the "Score" column will populate the table.

In [4]:

df = df.pivot(index="Name", columns="Subject", values="Score")

In [5]:
df

Subject  English  Math  Science
Name
Alice         88    85       90
Bob           85    78       82
Charlie       94    92       89

- In case of Duplicate Entries

In [6]:
# Create DataFrame from a list of dictionaries
data = [
    {"Name": "Alice", "Subject": "Math",    "Score": 85},
    {"Name": "Alice", "Subject": "Math",    "Score": 80},
    {"Name": "Alice", "Subject": "Science", "Score": 90},
    {"Name": "Bob",   "Subject": "Math",    "Score": 78},
    {"Name": "Bob",   "Subject": "Math",    "Score": 82},
]

df = pd.DataFrame(data)

print(df)

    Name  Subject  Score
0  Alice     Math     85
1  Alice     Math     80
2  Alice  Science     90
3    Bob     Math     78
4    Bob     Math     82

In [7]:
df.pivot_table(index="Name", columns="Subject", values="Score", aggfunc="mean")

Subject  Math  Science
Name
Alice    82.5     90.0
Bob      80.0      NaN

- If there are duplicate values for a given combination of index and columns, you should use pivot_table() with an aggregation function to handle the duplicates.