### Working with CSVs

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data2.csv")
df

      Actor       Film   Year      Genre  Box Office  IMDB
0       SRK      Pathan  2001     Action        1050   7.2
1    Salman       Tiger  2002     Action         456   9.8
2     Aamir      Dangal  2003  Biography         120   5.6
3    Akshay   Good News  2004     Comedy         100   5.6
4      Ajay     Singham  2005     Action         480   4.6
5     Varun        HSKD  2006     Action         456   7.8
6  Siddhant  Gehraiyaan  2007   Thriller         145   8.6
7     Vicky    Shiva Ji  2008     Action         254   3.2
8    Ranbir        YJHD  2009    Rom-Com         154   5.6
9   Ranveer   Dhurandar  2010     Action        1700  10.0

In [3]:
df = df[df['IMDB'] > 6.0]

In [4]:
df

      Actor       Film   Year     Genre  Box Office  IMDB
0       SRK      Pathan  2001    Action        1050   7.2
1    Salman       Tiger  2002    Action         456   9.8
5     Varun        HSKD  2006    Action         456   7.8
6  Siddhant  Gehraiyaan  2007  Thriller         145   8.6
9   Ranveer   Dhurandar  2010    Action        1700  10.0

In [5]:
# writing to a CSV 
df.to_csv("data_updates.csv")

In [6]:
df.to_csv("data_updated.csv", index=False)

In [7]:
df = pd.read_excel("data.xlsx")
df

     Name School   Marks
0      Om     SHS     87
1    Ajay    BNSD     45
2  Sachin    VSPS     87
3   Rahul     MHS     36
4   Sagar     UPS     46

In [8]:
df.to_excel("output.xlsx", index=False)

In [9]:
# DataFrame 1: Student scores
df1 = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie"],
    "Math": [85, 78, 92],
    "Science": [90, 88, 95]
})

# DataFrame 2: Employee information
df2 = pd.DataFrame({
    "Employee": ["John", "Emma", "Raj"],
    "Department": ["IT", "HR", "Finance"],
    "Salary": [60000, 55000, 70000]
})

print(df1)
print("\n")
print(df2)

      Name  Math  Science
0    Alice    85       90
1      Bob    78       88
2  Charlie    92       95


  Employee Department  Salary
0     John         IT   60000
1     Emma         HR   55000
2      Raj    Finance   70000

- for writing to multiple sheets

In [10]:
with pd.ExcelWriter("report.xlsx") as writer:
    df1.to_excel(writer, sheet_name="Student", index=False)
    df2.to_excel(writer, sheet_name="Employee", index=False)

In [11]:
df = pd.read_json("data.json")

In [12]:
df

    Name  Age
0     Om   21
1  Harry   40

In [13]:
df = pd.read_json("my_json.json")
df

   id   name                                  address
0   1  Alice   {'city': 'Delhi', 'zipcode': '110001'}
1   2    Bob  {'city': 'Mumbai', 'zipcode': '400001'}

In [14]:
my_data = [
    {"id": 1, "name": "Alice", "address": {"city": "Delhi", "zipcode": "110001"}},
    {"id": 2, "name": "Bob", "address": {"city": "Mumbai", "zipcode": "400001"}}
]

In [15]:
df = pd.json_normalize(my_data)

In [16]:
df

   id   name address.city address.zipcode
0   1  Alice        Delhi          110001
1   2    Bob       Mumbai          400001

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               2 non-null      int64
 1   name             2 non-null      object
 2   address.city     2 non-null      object
 3   address.zipcode  2 non-null      object
dtypes: int64(1), object(3)
memory usage: 196.0+ bytes